# Docker Compose Version
version: '3.9'

services:
  app:
    build: .
    volumes:
      - .:/django
    ports:
      - 8000:8000
    
    image: app:django
    container_name: django_docker

    command: sudo gunicorn docker_django.wsgi:application --bind 0.0.0.0:8000 --timeout=5 --threads=10
    
  nginx:
    build: ./nginx
    ports:
      - 80:80
    image: nginx:latest
    links:
      - app